# Generated by Django 4.1.3 on 2022-11-28 11:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('status', models.CharField(choices=[('I', 'initial'), ('C', 'needs captcha'), ('K', 'needs local checks'), ('L', 'needs remote checks'), ('M', 'needs invoice'), ('T', 'to_be_paid'), ('P', 'paid'), ('N', 'needs refund'), ('D', 'needs delete'), ('R', 'rejected'), ('F', 'fulfilled'), ('S', 'refunded'), ('A', 'archived')], default='I', max_length=1, verbose_name='Purchase Order Status')),
                ('message', models.CharField(blank=True, max_length=140, null=True, verbose_name='Message to Customer')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItemDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(help_text='The internal ID of the related Product.', max_length=50, null=True, verbose_name='Product ID (Char)')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Used for sorting', verbose_name='Position')),
                ('price', models.BigIntegerField(default=0, verbose_name='Price (in milli-satoshi) at time of purchase order')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='lnpurchase.purchaseorder')),
            ],
            options={
                'verbose_name': 'Purchase Order Item Detail',
                'verbose_name_plural': 'Purchase Order Item Details',
            },
        ),
    ]
