# Generated by Django 4.1.3 on 2022-11-28 11:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LndRestNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('is_enabled', models.BooleanField(default=True, help_text='Is enabled?', verbose_name='Is enabled?')),
                ('is_alive', models.BooleanField(default=False, editable=False, help_text='Is alive?', verbose_name='Is alive?')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='The lower the better: 0 is the highest and 32767 the lowest priority.', verbose_name='Priority')),
                ('name', models.CharField(default='MyNode', help_text='A friendly name (e.g. LND on MyNode @ Home).', max_length=128, verbose_name='Name')),
                ('hostname', models.CharField(default='localhost', help_text='Enter the hostname (FQDN) or IP address here. E.g. "localhost" or "127.0.0.1"', max_length=255, verbose_name='host')),
                ('tls_cert_verification', models.BooleanField(default=True, help_text='Verify TLS connections using the provided certificate? Should *always* be *enabled* in production.', verbose_name='TLS Verification')),
                ('tls_cert', models.TextField(blank=True, help_text='PEM encoded TLS Certificate as string (not bytes).', max_length=4096, null=True, verbose_name='TLS Certificate')),
                ('macaroon_admin', models.CharField(blank=True, help_text='Hex encoded macaroon as string (not bytes).', max_length=4096, null=True, verbose_name='Macaroon (Admin)')),
                ('macaroon_invoice', models.CharField(blank=True, help_text='Hex encoded macaroon as string (not bytes).', max_length=4096, null=True, verbose_name='Macaroon (Invoice)')),
                ('macaroon_readonly', models.CharField(blank=True, help_text='Hex encoded macaroon as string (not bytes).', max_length=4096, null=True, verbose_name='Macaroon (Readonly)')),
                ('port', models.IntegerField(default=8080, help_text='Port REST interface. Must be in range 1 - 65535. Default: 8080.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='port')),
                ('owner', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'LND REST Node',
                'verbose_name_plural': 'LND REST Nodes',
                'ordering': ('-priority',),
            },
        ),
        migrations.CreateModel(
            name='FakeNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('is_enabled', models.BooleanField(default=True, help_text='Is enabled?', verbose_name='Is enabled?')),
                ('is_alive', models.BooleanField(default=False, editable=False, help_text='Is alive?', verbose_name='Is alive?')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='The lower the better: 0 is the highest and 32767 the lowest priority.', verbose_name='Priority')),
                ('name', models.CharField(default='MyNode', help_text='A friendly name (e.g. LND on MyNode @ Home).', max_length=128, verbose_name='Name')),
                ('owner', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Fake Node',
                'verbose_name_plural': 'Fake Nodes',
                'ordering': ('-priority',),
            },
        ),
        migrations.CreateModel(
            name='CLightningNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('is_enabled', models.BooleanField(default=True, help_text='Is enabled?', verbose_name='Is enabled?')),
                ('is_alive', models.BooleanField(default=False, editable=False, help_text='Is alive?', verbose_name='Is alive?')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='The lower the better: 0 is the highest and 32767 the lowest priority.', verbose_name='Priority')),
                ('name', models.CharField(default='MyNode', help_text='A friendly name (e.g. LND on MyNode @ Home).', max_length=128, verbose_name='Name')),
                ('socket_path', models.CharField(default='/root/.lightning/lightning-rpc', help_text='Enter the unix socket path here. E.g. "~/.lightning/lightning-rpc"', max_length=255, verbose_name='Socket Path')),
                ('owner', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'c-lightning Node',
                'verbose_name_plural': 'c-lightning Nodes',
                'ordering': ('-priority',),
            },
        ),
        migrations.CreateModel(
            name='LndGRpcNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('is_enabled', models.BooleanField(default=True, help_text='Is enabled?', verbose_name='Is enabled?')),
                ('is_alive', models.BooleanField(default=False, editable=False, help_text='Is alive?', verbose_name='Is alive?')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='The lower the better: 0 is the highest and 32767 the lowest priority.', verbose_name='Priority')),
                ('name', models.CharField(default='MyNode', help_text='A friendly name (e.g. LND on MyNode @ Home).', max_length=128, verbose_name='Name')),
                ('hostname', models.CharField(default='localhost', help_text='Enter the hostname (FQDN) or IP address here. E.g. "localhost" or "127.0.0.1"', max_length=255, verbose_name='host')),
                ('tls_cert_verification', models.BooleanField(default=True, help_text='Verify TLS connections using the provided certificate? Should *always* be *enabled* in production.', verbose_name='TLS Verification')),
                ('tls_cert', models.TextField(blank=True, help_text='PEM encoded TLS Certificate as string (not bytes).', max_length=4096, null=True, verbose_name='TLS Certificate')),
                ('macaroon_admin', models.CharField(blank=True, help_text='Hex encoded macaroon as string (not bytes).', max_length=4096, null=True, verbose_name='Macaroon (Admin)')),
                ('macaroon_invoice', models.CharField(blank=True, help_text='Hex encoded macaroon as string (not bytes).', max_length=4096, null=True, verbose_name='Macaroon (Invoice)')),
                ('macaroon_readonly', models.CharField(blank=True, help_text='Hex encoded macaroon as string (not bytes).', max_length=4096, null=True, verbose_name='Macaroon (Readonly)')),
                ('port', models.IntegerField(default=10009, help_text='Port gRPC interface. Must be in range 1 - 65535. Default: 10009.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='port')),
                ('owner', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'LND gRPC Node',
                'verbose_name_plural': 'LND gRPC Nodes',
                'ordering': ('-priority',),
                'unique_together': {('hostname', 'port')},
            },
        ),
    ]
