# Generated by Django 4.1.4 on 2023-01-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(help_text='IP Address of Host.', verbose_name='IP Address'),
        ),
    ]
