# Generated by Django 4.1.5 on 2023-01-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_host_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='description',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='What is offered in this Host'),
        ),
    ]
