# Generated by Django 4.1.5 on 2023-01-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_host_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='description',
            field=models.CharField(blank=True, help_text='What is offered in this host.', max_length=140, null=True, verbose_name='Description'),
        ),
    ]
