# Generated by Django 4.1.5 on 2023-02-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_host_nostr_alias_duration_host_nostr_alias_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='nostr_alias_port',
            field=models.PositiveIntegerField(default=80, help_text='At which port will the host access the Nostr Aliases. E.g. nostr_alias.com:80', verbose_name='Nostr Alias Port'),
        ),
    ]
