# Generated by Django 4.1.5 on 2023-06-08 20:34

import django.core.validators
from django.db import migrations, models
import re
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_nostralias_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='bridge_bandwidth_initial',
            field=models.BigIntegerField(default=1073741824, help_text='Max traffic allowed (bandwidth in bytes) during the life of the bridges in this host.', verbose_name='Bridge bandwidth allocated initially (bytes)'),
        ),
        migrations.AddField(
            model_name='nostralias',
            name='bandwidth_last_checked',
            field=models.DateTimeField(blank=True, help_text='Last time bandwidth usage was checked in this bridge', null=True, verbose_name='Last time bandwidth usage was checked in this bridge'),
        ),
        migrations.AddField(
            model_name='nostralias',
            name='bandwidth_remaining',
            field=models.BigIntegerField(default=1073741824, help_text='Remaining amount of traffic allowed (bandwidth in bytes) during the life of this bridge. Initialized with the default bandwidth allocation of the Host', verbose_name='Remaining traffic allocation (bandwidth in bytes)'),
        ),
        migrations.AddField(
            model_name='rsshtunnel',
            name='bandwidth_last_checked',
            field=models.DateTimeField(blank=True, help_text='Last time bandwidth usage was checked in this bridge', null=True, verbose_name='Last time bandwidth usage was checked in this bridge'),
        ),
        migrations.AddField(
            model_name='rsshtunnel',
            name='bandwidth_remaining',
            field=models.BigIntegerField(default=1073741824, help_text='Remaining amount of traffic allowed (bandwidth in bytes) during the life of this bridge. Initialized with the default bandwidth allocation of the Host', verbose_name='Remaining traffic allocation (bandwidth in bytes)'),
        ),
        migrations.AddField(
            model_name='torbridge',
            name='bandwidth_last_checked',
            field=models.DateTimeField(blank=True, help_text='Last time bandwidth usage was checked in this bridge', null=True, verbose_name='Last time bandwidth usage was checked in this bridge'),
        ),
        migrations.AddField(
            model_name='torbridge',
            name='bandwidth_remaining',
            field=models.BigIntegerField(default=1073741824, help_text='Remaining amount of traffic allowed (bandwidth in bytes) during the life of this bridge. Initialized with the default bandwidth allocation of the Host', verbose_name='Remaining traffic allocation (bandwidth in bytes)'),
        ),
        migrations.AlterField(
            model_name='nostralias',
            name='alias',
            field=models.CharField(help_text='Alias for your Nostr public key (allowed only letters, numbers, underscore and hyphens).', max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid'), shop.validators.validate_nostr_alias_blacklist], verbose_name='Nostr Alias'),
        ),
    ]
