# Generated by Django 4.1.5 on 2023-06-10 02:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_host_bridge_bandwidth_initial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandwidthExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total', models.BigIntegerField(default=1073741824, help_text='Total amount of traffic allowed (bandwidth in bytes) during the life of this extension, that is, before its expiry date.', verbose_name='Initial purchased extension (bandwidth in bytes)')),
                ('remaining', models.BigIntegerField(default=1073741824, help_text='Remaining amount of traffic allowed (bandwidth in bytes) during the life of this extension.', verbose_name='Remaining traffic allocation (bandwidth in bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this extension was purchased (after successful payment)', verbose_name='Date of purchase')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this extension was last updated (usually to modify the remaining bandwidth)', verbose_name='Date of last update')),
                ('expires_at', models.DateTimeField(blank=True, help_text='The extension will only be valid before the expiry date', null=True, verbose_name='Expiry date')),
                ('tor_bridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.torbridge')),
            ],
        ),
    ]
