# Generated by Django 4.1.5 on 2023-06-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_bandwidthextension_tor_bridge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandwidthextensionoption',
            name='host',
        ),
        migrations.AddField(
            model_name='bandwidthextensionoption',
            name='hosts',
            field=models.ManyToManyField(related_name='bandwidth_extension_options', to='shop.host'),
        ),
    ]
