# Generated by Django 4.1.5 on 2023-11-05 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_nostralias_status_alter_rsshtunnel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nostralias',
            name='bandwidth_last_checked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 5, 11, 15, 57, 549942, tzinfo=datetime.timezone.utc), help_text='Last time bandwidth usage was checked in this bridge', null=True, verbose_name='Last time bandwidth usage was checked in this bridge'),
        ),
        migrations.AlterField(
            model_name='rsshtunnel',
            name='bandwidth_last_checked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 5, 11, 15, 57, 549942, tzinfo=datetime.timezone.utc), help_text='Last time bandwidth usage was checked in this bridge', null=True, verbose_name='Last time bandwidth usage was checked in this bridge'),
        ),
        migrations.AlterField(
            model_name='torbridge',
            name='bandwidth_last_checked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 5, 11, 15, 57, 549942, tzinfo=datetime.timezone.utc), help_text='Last time bandwidth usage was checked in this bridge', null=True, verbose_name='Last time bandwidth usage was checked in this bridge'),
        ),
    ]
