# Generated by Django 4.1.5 on 2024-02-13 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_nostralias_bandwidth_last_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nostralias',
            name='bandwidth_last_checked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 13, 8, 43, 5, 618729, tzinfo=datetime.timezone.utc), help_text='Last time bandwidth usage was checked in this bridge', null=True, verbose_name='Last time bandwidth usage was checked in this bridge'),
        ),
        migrations.AlterField(
            model_name='rsshtunnel',
            name='bandwidth_last_checked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 13, 8, 43, 5, 618729, tzinfo=datetime.timezone.utc), help_text='Last time bandwidth usage was checked in this bridge', null=True, verbose_name='Last time bandwidth usage was checked in this bridge'),
        ),
        migrations.AlterField(
            model_name='torbridge',
            name='bandwidth_last_checked',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 13, 8, 43, 5, 618729, tzinfo=datetime.timezone.utc), help_text='Last time bandwidth usage was checked in this bridge', null=True, verbose_name='Last time bandwidth usage was checked in this bridge'),
        ),
    ]
